# Generated by Django 4.1 on 2022-08-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='test',
        ),
    ]
