# Generated by Django 4.1 on 2022-08-26 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_item_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='email',
            field=models.EmailField(default=0.001123876123876124, max_length=200),
            preserve_default=False,
        ),
    ]
