# Generated by Django 4.1 on 2022-08-26 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_test_dob_test_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='colleges',
            fields=[
                ('colleges_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('colleges_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('students_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('students_first_name', models.CharField(max_length=200)),
                ('students_last_name', models.CharField(max_length=200)),
                ('students_phone', models.IntegerField(max_length=10)),
                ('students_email', models.EmailField(max_length=200)),
                ('students_address', models.CharField(max_length=200)),
                ('colleges_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.colleges')),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('subjects_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subjects_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subjects_students',
            fields=[
                ('subjects_students_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('students_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.students')),
                ('subjects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.subjects')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
