# Generated by Django 4.1 on 2022-08-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_colleges_students_subjects_subjects_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='students_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='students_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='students_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='students_last_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='students_phone',
        ),
        migrations.AddField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='studentts', to='playground.subjects'),
        ),
        migrations.DeleteModel(
            name='subjects_students',
        ),
    ]
