# Generated by Django 4.1 on 2022-08-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_rename_students_address_students_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='colleges',
            new_name='College',
        ),
        migrations.RenameModel(
            old_name='students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='subjects',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='colleges_id',
            new_name='college_id',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='colleges_name',
            new_name='college_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='colleges_id',
            new_name='college_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='students_id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subjects_id',
            new_name='subject_id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subjects_name',
            new_name='subject_name',
        ),
    ]
